### ISSUE TITLE
[hint] Different mssql images in Labs 2 and 3

### ISSUE THREAD

**Issue by Tuumke** [XpiritBV/ContainerWorkshop2019Docs#12]
https://github.com/XpiritBV/ContainerWorkshop2019Docs/blob/master/Lab2-Docker101.md
uses image:
`mcr.microsoft.com/mssql/server:2017-latest-ubuntu`

https://github.com/XpiritBV/ContainerWorkshop2019Docs/blob/master/Lab3-DockerizingNETCore.md
uses image:
`mcr.microsoft.com/mssql/server:2017-CU8-ubuntu`

Can be a lot on small internet lines since the image is quit large.

**Comment by loekd** [comment]
Thanks!
We made this consistent during the upgrade
