### ISSUE TITLE
[question] Lab 3

### ISSUE THREAD

**Issue by Tuumke** [XpiritBV/ContainerWorkshop2019Docs#13]
Today in our course we were doing Lab 3 but sort-of skipped it to Lab 4 - Networking.

So doing Lab3 now but..

https://github.com/XpiritBV/ContainerWorkshop2019Docs/blob/master/Lab3-DockerizingNETCore.md
Lab 3 states:

> You will learn more on networking later on. For now, notice that the URL is not referring to localhost but leaderboardwebapi (the name of the Docker container service as defined in the docker-compose.yml file).

But... its not. Not anywhere i can find.  Unless i am looking in the wrong location, but the text suggest that you should be looking in the docker-compose.yml, maybe the docker-compose.override.yml.

Then reading on the text says:

> Change the LeaderboardWebApiBaseUrl setting to point to the new endpoint of the Web API with the internal address http://leaderboard.webapi.

> Make sure you use the HTTP endpoint, because hosting an HTTPS endpoint with self-signed certificates in a cluster does not work by default.

> Choose the right place to make that change, considering that you are now running from Docker containers.

> Hint
> Changing the setting in the appsettings.json file will work and you could choose to do so for now. It does mean that the setting for running without container will not work anymore. So, what other place can you think of that might work? Use that instead if you know, or just change appsettings.json.

> gamingwebapp:
  environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - LeaderboardApiOptions:BaseUrl=http://leaderboard.webapi

So, is it saying leaderboardwepai instead of localhost anywhere? Or.. am i misreading this?

**Comment by loekd** [comment]
Thanks, we've fixed this.
The environment variable named `LeaderboardApiOptions:BaseUrl`  incorrectly specified that there's a host named `leaderboard.webapi`, we've changed this into `leaderboardwebapi`.
