### ISSUE TITLE
Lab07: remove part about Kubernetes Dashboard

### ISSUE THREAD

**Issue by roycornelissen** [XpiritBV/ContainerWorkshop2019Docs#17]
The installation of the [Kubernetes Dashboard](https://github.com/XpiritBV/ContainerWorkshop-Docs/blob/master/Lab7-RegistriesClusters.md#connecting-to-your-cluster) in Lab07 is a bit of a distraction, with all the hassle of obtaining a token and copy/pasting it into the login screen. There are better ways to connect to your cluster (`az aks get credentials`) and other tools that you can use like the VS Code extension, Lens or even the Azure Portal.

I suggest removing this section.

**Comment by loekd** [comment]
Done
